export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/paymentMethod";
export * from "@/pages/dashboard/menu";
export * from "@/pages/dashboard/accessManagement";
export * from "@/pages/dashboard/cash";
export * from "@/pages/dashboard/diningTable";
export * from "@/pages/dashboard/tax";
export * from "@/pages/dashboard/visit";
